services:
  cypress:
    build:
      context: ../../dockerfiles/cypress
      args:
        - USER_UID
        - USER_GID
    volumes:
      - ../../:/overleaf
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY:-/dev/null}:/home/node/.Xauthority
    working_dir: /overleaf/services/web
    entrypoint: npm
    command: run cypress:open-ct
    environment:
      VERBOSE_LOGGING:
      DISPLAY: ${DISPLAY:-:0}
#      DEBUG: cypress.*
